#include <tone.h>
#include <chushan.h>
#include <delay_by_systick.h>

void chushan(void)
{
	while(1)
	{
		middle_mi();	
		delay_ms(300);
		middle_mi();
		delay_ms(250);
		middle_mi();
		delay_ms(300);
		middle_mi();
		delay_ms(250);
		middle_mi();
		delay_ms(300);
		middle_mi();
		delay_ms(250);
		middle_mi();
		delay_ms(300);
		middle_re();
		delay_ms(400);
	
		middle_re();
		delay_ms(300);
		middle_do();
		delay_ms(250);
		middle_do();
		delay_ms(300);
		middle_la();
		delay_ms(250);
		middle_re();
		delay_ms(300);
		middle_mi();
		delay_ms(250);
		middle_mi();
		delay_ms(400);
	
		middle_mi();	
		delay_ms(300);
		middle_mi();
		delay_ms(250);
		middle_mi();
		delay_ms(300);
		middle_mi();
		delay_ms(250);
		middle_so();
		delay_ms(300);
		middle_mi();
		delay_ms(250);
		middle_re();
		delay_ms(300);
		middle_mi();
		delay_ms(400);
	
		middle_re();
		delay_ms(300);
		middle_do();
		delay_ms(250);
		middle_do();
		delay_ms(300);
		middle_la();
		delay_ms(250);
		middle_do();
		delay_ms(300);
		middle_re();
		delay_ms(250);
		middle_re();
		delay_ms(100);
		middle_la();
		delay_ms(400);
	
		middle_mi();
		delay_ms(300);		
		middle_mi();
		delay_ms(250);
		middle_mi();
		delay_ms(300);
		middle_do();
		delay_ms(250);
		middle_re();
		delay_ms(300);
		middle_mi();
		delay_ms(250);		
		middle_mi();
		delay_ms(400);
		
		middle_mi();
		delay_ms(300);
		middle_do();
		delay_ms(250);
		middle_do();
		delay_ms(300);
		middle_la();
		delay_ms(250);
		middle_do();
		delay_ms(300);
		middle_mi();
		delay_ms(250);
		middle_mi();
		delay_ms(400);
		
		middle_mi();
		delay_ms(300);
		middle_mi();
		delay_ms(250);
		middle_mi();
		delay_ms(300);
		middle_mi();
		delay_ms(250);
		middle_so();
		delay_ms(300);
		middle_mi();
		delay_ms(250);
		middle_re();
		delay_ms(300);
		middle_do();
		delay_ms(400);
		
		middle_re();
		delay_ms(300);
		middle_do();
		delay_ms(250);
		middle_do();
		delay_ms(300);
		middle_la();
		delay_ms(250);
		middle_do();
		delay_ms(300);
		middle_re();
		delay_ms(250);
		middle_do();
		delay_ms(400);
		
		middle_do();
		delay_ms(300);
		middle_do();
		delay_ms(250);
		middle_si();
		delay_ms(300);
		middle_do();
		delay_ms(250);
		low_si();
		delay_ms(450);
		low_so();
		delay_ms(400);
		
		low_la();
		delay_ms(300);
		middle_do();
		delay_ms(250);
		middle_do();
		delay_ms(400);
		middle_re();
		delay_ms(300);
		middle_mi();
		delay_ms(250);
		middle_fa();
		delay_ms(300);
		middle_mi();
		delay_ms(400);
		
		middle_do();
		delay_ms(300);
		middle_do();
		delay_ms(250);
		low_si();
		delay_ms(300);
		middle_do();
		delay_ms(250);
		low_si();
		delay_ms(550);
		low_so();
		delay_ms(400);
		
		low_la();
		delay_ms(300);
		middle_do();
		delay_ms(250);
		middle_do();
		delay_ms(300);
		middle_do();
		delay_ms(250);
		middle_re();
		delay_ms(300);
		middle_mi();
		delay_ms(250);
		middle_fa();
		delay_ms(300);
		middle_mi();
		delay_ms(300);
	}

}
